version: '3.7'

services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src/:/app_name
    ports:
      - "3000:3000"
    networks:
      rails-app-net:
        ipv4_address: 172.30.1.2

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    networks:
      rails-app-net:
        ipv4_address: 172.30.1.3

networks:
  rails-app-net:
    name: rails-app-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
