version: '3.7'

services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src/:/app_name
    ports:
      - "3000:3000"
    networks:
      rails-app-net:
        ipv4_address: 172.30.1.2

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-db:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    networks:
      rails-app-net:
        ipv4_address: 172.30.1.3

  redis:
    image: "redis:latest"
    volumes:
      - redis-data:/data
    networks:
      rails-app-net:
        ipv4_address: 172.30.1.4

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    networks:
      rails-app-net:
        ipv4_address: 172.30.1.5

volumes:
  mysql-db:
    driver: local
  redis-data:
    driver: local

networks:
  rails-app-net:
    name: rails-app-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
